/**
 * Predictive Action Queuing — pre-stages actions before the user asks.
 *
 * Runs every 10 minutes. Analyzes the full context (persona, calendar,
 * routines, observations, life events, relationships, commitments) and
 * predicts what actions will be needed in the next 24-72 hours.
 *
 * Predicted actions sit in pending_actions, NOT surfaced automatically.
 * They're served when:
 * - User asks "anything I need to do?" or "what's coming up?"
 * - The trigger moment arrives (calendar event starts, deadline passes)
 * - A life event or severe routine break forces regeneration
 *
 * Action types:
 * - meeting_briefing: pre-generated briefing for upcoming calendar events
 * - follow_up_draft: draft emails for stale threads approaching critical
 * - commitment_reminder: recurring commitments coming due
 * - routine_recovery: proposed actions for broken routines
 * - conflict_resolution: calendar conflict proposals
 * - relationship_maintenance: contacts at risk of going cold
 * - deadline_preparation: tasks approaching their due dates
 */

import { getPool, getSettings, getLivingProfile } from './db'
import crypto from 'crypto'

// ── Types ─────────────────────────────────────────────────────────

interface PredictedAction {
  triggerContext: string
  triggerType: string
  actionType: string
  title: string
  description: string
  draftContent: string | null
  confidence: number
  urgency: 'critical' | 'high' | 'medium' | 'low'
  expiresAt: string
  relatedEntity: string | null
  evidence: string[]
}

// ── Main: predict actions for the next 24-72h ─────────────────────

export async function runActionPredictor(): Promise<number> {
  const pool = getPool()
  const now = new Date()
  const predictions: PredictedAction[] = []

  console.log('[predictor] Scanning for predictable actions...')

  // ── 1. Stale threads approaching critical ───────────────────────
  // Threads stale 7+ days → draft follow-up emails

  const staleThreads = await pool.query(
    "SELECT thread_id, subject, last_message_from, stale_days, participants FROM email_threads WHERE stale_days >= 7 ORDER BY stale_days DESC LIMIT 10"
  )

  for (const thread of staleThreads.rows) {
    const alreadyPredicted = await pool.query(
      "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending' AND expires_at > NOW()",
      [`thread-${thread.thread_id}`]
    )
    if (alreadyPredicted.rows.length > 0) continue

    const urgency = thread.stale_days > 14 ? 'critical' : thread.stale_days > 10 ? 'high' : 'medium'
    const participants = safeParseJson(thread.participants, [])
    const recipient = thread.last_message_from || (participants.length > 0 ? participants[0] : null)

    predictions.push({
      triggerContext: `Email thread "${thread.subject}" has been stale for ${thread.stale_days} days`,
      triggerType: 'stale_thread',
      actionType: 'follow_up_draft',
      title: `Follow up: ${thread.subject}`,
      description: `Draft a follow-up email for "${thread.subject}" — ${thread.stale_days} days without response from ${recipient || 'recipient'}`,
      draftContent: null, // Will be generated by Claude below
      confidence: 0.8,
      urgency: urgency as any,
      expiresAt: new Date(now.getTime() + 72 * 3600000).toISOString(),
      relatedEntity: `thread-${thread.thread_id}`,
      evidence: [`Stale for ${thread.stale_days} days`, `Last from: ${thread.last_message_from}`]
    })
  }

  // ── 2. Calendar events in next 48h → meeting briefings ──────────

  const upcomingEvents = await pool.query(
    `SELECT id, summary, start_time, end_time, participants, location
     FROM calendar_events
     WHERE start_time::timestamptz >= NOW()
     AND start_time::timestamptz <= NOW() + INTERVAL '48 hours'
     AND status != 'cancelled'
     ORDER BY start_time::timestamptz`
  )

  for (const event of upcomingEvents.rows) {
    const alreadyPredicted = await pool.query(
      "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending' AND expires_at > NOW()",
      [`event-${event.id}`]
    )
    if (alreadyPredicted.rows.length > 0) continue

    const participants = safeParseJson(event.participants, [])
    const hoursUntil = Math.round((new Date(event.start_time).getTime() - now.getTime()) / 3600000)

    predictions.push({
      triggerContext: `"${event.summary}" starts in ${hoursUntil} hours`,
      triggerType: 'calendar_event',
      actionType: 'meeting_briefing',
      title: `Prepare for: ${event.summary}`,
      description: `Meeting "${event.summary}" in ${hoursUntil}h${participants.length > 0 ? ` with ${participants.join(', ')}` : ''}${event.location ? ` at ${event.location}` : ''}`,
      draftContent: null,
      confidence: 0.9,
      urgency: hoursUntil < 6 ? 'high' : 'medium',
      expiresAt: event.start_time,
      relatedEntity: `event-${event.id}`,
      evidence: [`Calendar event: ${event.summary}`, `Start: ${event.start_time}`, participants.length > 0 ? `With: ${participants.join(', ')}` : ''].filter(Boolean)
    })
  }

  // ── 3. Commitments approaching due dates ────────────────────────

  // Safe: some due_at values are free-text ("April 6-10th"), not ISO timestamps
  // Use a subquery that catches cast errors
  let dueSoon: { rows: any[] } = { rows: [] }
  try {
    dueSoon = await pool.query(
      `SELECT id, description, due_at, committed_to, source_type FROM commitments
       WHERE status = 'active' AND due_at IS NOT NULL
       AND due_at ~ '^\\d{4}-\\d{2}-\\d{2}'
       AND due_at::timestamptz <= NOW() + INTERVAL '72 hours'
       AND due_at::timestamptz >= NOW()`
    )
  } catch {
    // If any cast fails, just skip commitment predictions
    console.warn('[predictor] Skipping commitment due-date predictions (non-ISO dates in table)')
  }

  for (const c of dueSoon.rows) {
    const alreadyPredicted = await pool.query(
      "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending'",
      [`commitment-${c.id}`]
    )
    if (alreadyPredicted.rows.length > 0) continue

    const hoursUntil = Math.round((new Date(c.due_at).getTime() - now.getTime()) / 3600000)

    predictions.push({
      triggerContext: `Commitment due in ${hoursUntil} hours: "${c.description}"`,
      triggerType: 'commitment_due',
      actionType: 'commitment_reminder',
      title: `Due soon: ${c.description.slice(0, 60)}`,
      description: `Commitment "${c.description}" due in ${hoursUntil}h${c.committed_to ? ` (to: ${c.committed_to})` : ''}`,
      draftContent: null,
      confidence: 0.85,
      urgency: hoursUntil < 12 ? 'critical' : 'high',
      expiresAt: c.due_at,
      relatedEntity: `commitment-${c.id}`,
      evidence: [`Due: ${c.due_at}`, `Source: ${c.source_type}`, c.committed_to ? `To: ${c.committed_to}` : ''].filter(Boolean)
    })
  }

  // ── 4. Routine breaks needing recovery ──────────────────────────

  const severeBreaks = await pool.query(
    "SELECT id, description, expected_behavior, actual_behavior, days_broken, severity FROM routine_breaks WHERE severity IN ('high', 'medium') AND detected_at >= NOW() - INTERVAL '7 days' ORDER BY days_broken DESC LIMIT 5"
  )

  for (const b of severeBreaks.rows) {
    const alreadyPredicted = await pool.query(
      "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending'",
      [`break-${b.id}`]
    )
    if (alreadyPredicted.rows.length > 0) continue

    predictions.push({
      triggerContext: `Routine broken for ${b.days_broken} days: ${b.description}`,
      triggerType: 'routine_break',
      actionType: 'routine_recovery',
      title: `Recover routine: ${b.description.slice(0, 60)}`,
      description: `${b.description}. Expected: ${b.expected_behavior}. Actual: ${b.actual_behavior}. Broken for ${b.days_broken} days.`,
      draftContent: null,
      confidence: 0.6,
      urgency: b.severity === 'high' ? 'high' : 'medium',
      expiresAt: new Date(now.getTime() + 72 * 3600000).toISOString(),
      relatedEntity: `break-${b.id}`,
      evidence: [`${b.days_broken} days broken`, `Severity: ${b.severity}`]
    })
  }

  // ── 5. Relationships at risk ────────────────────────────────────

  const atRiskRels = await pool.query(
    `SELECT name, email, current_closeness, trajectory, anomaly, narrative_note
     FROM relationships
     WHERE (anomaly IN ('overdue_followup', 'sudden_silence') OR trajectory = 'declining')
     AND current_closeness > 25
     ORDER BY current_closeness DESC LIMIT 5`
  )

  for (const r of atRiskRels.rows) {
    const alreadyPredicted = await pool.query(
      "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending'",
      [`rel-${r.email}`]
    )
    if (alreadyPredicted.rows.length > 0) continue

    predictions.push({
      triggerContext: `Relationship with ${r.name} is ${r.trajectory}${r.anomaly ? ` (${r.anomaly.replace(/_/g, ' ')})` : ''}`,
      triggerType: 'relationship_risk',
      actionType: 'relationship_maintenance',
      title: `Reach out to ${r.name}`,
      description: r.narrative_note || `${r.name} — closeness ${r.current_closeness}/100, trajectory: ${r.trajectory}`,
      draftContent: null,
      confidence: 0.65,
      urgency: r.anomaly === 'sudden_silence' ? 'high' : 'medium',
      expiresAt: new Date(now.getTime() + 72 * 3600000).toISOString(),
      relatedEntity: `rel-${r.email}`,
      evidence: [`Closeness: ${r.current_closeness}/100`, `Trajectory: ${r.trajectory}`, r.anomaly ? `Anomaly: ${r.anomaly}` : ''].filter(Boolean)
    })
  }

  // ── 6. Centrum Today items not started ──────────────────────────

  const centrumSnap = await pool.query(
    "SELECT board_state FROM centrum_snapshots ORDER BY timestamp DESC LIMIT 1"
  )

  if (centrumSnap.rows.length > 0) {
    const board = centrumSnap.rows[0].board_state
    const todayIds = new Set(board.todayIds || [])
    const todayDone = new Set(board.todayDone || [])
    const cards = board.cards || []
    const clusters = cards.filter((c: any) => c.type === 'cluster')

    for (const cardId of todayIds) {
      if (todayDone.has(cardId)) continue
      const card = cards.find((c: any) => c.id === cardId)
      if (!card) continue

      const alreadyPredicted = await pool.query(
        "SELECT id FROM predicted_actions WHERE related_entity = $1 AND status = 'pending'",
        [`centrum-${card.id}`]
      )
      if (alreadyPredicted.rows.length > 0) continue

      const cluster = clusters.find((c: any) => c.id === card.clusterId)?.title || 'Unclustered'
      const subtasks = Array.isArray(card.content) ? card.content : []
      const undone = subtasks.filter((s: any) => !s.done)

      predictions.push({
        triggerContext: `Centrum Today item not started: "${card.title}" [${cluster}]`,
        triggerType: 'centrum_today',
        actionType: 'deadline_preparation',
        title: `Start: ${card.title} [${cluster}]`,
        description: `Today list item "${card.title}" in ${cluster}${undone.length > 0 ? `. Remaining subtasks: ${undone.map((s: any) => s.text).join(', ')}` : ''}`,
        draftContent: null,
        confidence: 0.75,
        urgency: 'medium',
        expiresAt: new Date(now.getTime() + 24 * 3600000).toISOString(), // expires end of day
        relatedEntity: `centrum-${card.id}`,
        evidence: [`In Today list`, `Cluster: ${cluster}`, undone.length > 0 ? `${undone.length} subtasks remaining` : ''].filter(Boolean)
      })
    }
  }

  if (predictions.length === 0) {
    console.log('[predictor] No new actions predicted')
    return 0
  }

  // ── Generate draft content for top predictions via Claude ───────

  const settings = await getSettings()
  const apiKey = settings.api_key || process.env.ANTHROPIC_API_KEY

  if (apiKey) {
    await generateDrafts(apiKey, settings.model, predictions)
  }

  // ── Store predictions (with dedup) ──────────────────────────────

  // Expire old predictions
  await pool.query(
    "UPDATE predicted_actions SET status = 'expired' WHERE status = 'pending' AND expires_at < NOW()"
  )

  // Cleanup existing duplicates: keep only the oldest per normalized title
  await pool.query(`
    DELETE FROM predicted_actions WHERE id IN (
      SELECT id FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY LOWER(TRIM(title)) ORDER BY predicted_at ASC) as rn
        FROM predicted_actions WHERE status = 'pending'
      ) dupes WHERE rn > 1
    )
  `)

  let stored = 0
  for (const p of predictions) {
    // Dedup: check if an equivalent action exists (same normalized title, pending, within 24h)
    const normalizedTitle = p.title.toLowerCase().trim()
    const existing = await pool.query(
      "SELECT id FROM predicted_actions WHERE LOWER(TRIM(title)) = $1 AND status = 'pending' AND predicted_at > NOW() - INTERVAL '24 hours'",
      [normalizedTitle]
    )
    if (existing.rows.length > 0) continue // skip duplicate

    const id = crypto.randomUUID()
    await pool.query(
      `INSERT INTO predicted_actions (id, trigger_context, trigger_type, action_type, title, description,
        draft_content, confidence, urgency, expires_at, related_entity, evidence)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
      [id, p.triggerContext, p.triggerType, p.actionType, p.title, p.description,
        p.draftContent, p.confidence, p.urgency, p.expiresAt,
        p.relatedEntity, JSON.stringify(p.evidence)]
    )
    stored++
  }

  console.log(`[predictor] Stored ${stored} predicted actions (${predictions.filter(p => p.draftContent).length} with drafts)`)
  return stored
}

// ── Generate drafts for high-priority predictions ─────────────────

async function generateDrafts(apiKey: string, model: string, predictions: PredictedAction[]): Promise<void> {
  // Only draft for follow-ups and meeting briefings (the ones where pre-staging saves the most time)
  const toDraft = predictions.filter(p =>
    p.actionType === 'follow_up_draft' || p.actionType === 'meeting_briefing'
  ).slice(0, 5) // max 5 drafts per run

  if (toDraft.length === 0) return

  const persona = await getLivingProfile()

  try {
    const Anthropic = (await import('@anthropic-ai/sdk')).default
    const { claudeWithFallback } = await import('./claude-fallback')
    const client = new Anthropic({ apiKey })

    for (const pred of toDraft) {
      try {
        let prompt = ''
        let systemMsg = ''

        if (pred.actionType === 'follow_up_draft') {
          systemMsg = `You are drafting a follow-up email on behalf of Kavin. Match his actual communication style:
- Casual with peers and academic contacts (not "Dear Sir", use "Hey" or first name)
- Direct and brief — 2-4 sentences
- No corporate filler ("I hope this finds you well")
- Reference the specific thing being followed up on
- End with a clear ask or proposed next step

${persona ? `About Kavin:\n${persona.slice(0, 500)}` : ''}`

          prompt = `Draft a follow-up for: ${pred.description}\n\nEvidence: ${pred.evidence.join('. ')}`
        } else if (pred.actionType === 'meeting_briefing') {
          systemMsg = `Generate a concise meeting briefing for Kavin. Include:
- Who's attending and their relationship to Kavin
- What's likely on the agenda (based on recent interactions)
- Any open threads or stale items with attendees
- One thing Kavin should prepare or decide

Keep it to 3-5 bullet points. Be specific, not generic.

${persona ? `About Kavin:\n${persona.slice(0, 500)}` : ''}`

          prompt = `Brief me for: ${pred.description}\n\nContext: ${pred.triggerContext}`
        }

        if (!prompt) continue

        const response = await claudeWithFallback(client, {
          model: model || 'claude-sonnet-4-20250514',
          max_tokens: 300,
          system: systemMsg,
          messages: [{ role: 'user', content: prompt }]
        }, 'action-predictor')

        const draft = response.content[0].type === 'text' ? response.content[0].text : ''
        if (draft.length > 10) {
          pred.draftContent = draft
        }
      } catch (err: any) {
        console.warn(`[predictor] Draft generation failed for "${pred.title}":`, err.message)
      }
    }
  } catch (err: any) {
    console.error('[predictor] Claude init failed:', err.message)
  }
}

// ── Get pending actions for context injection ─────────────────────

export async function getPendingActions(limit: number = 10): Promise<any[]> {
  const pool = getPool()
  const r = await pool.query(
    `SELECT id, title, description, action_type, urgency, confidence, draft_content,
            trigger_context, expires_at, related_entity
     FROM predicted_actions
     WHERE status = 'pending' AND expires_at > NOW()
     ORDER BY
       CASE urgency WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,
       confidence DESC
     LIMIT $1`,
    [limit]
  )
  return r.rows
}

export async function markActionServed(actionId: string, query: string): Promise<void> {
  const pool = getPool()
  await pool.query(
    "UPDATE predicted_actions SET status = 'served', served_at = NOW(), served_in_query = $2 WHERE id = $1",
    [actionId, query.slice(0, 200)]
  )
}

// ── Format for context injection ──────────────────────────────────

export function formatPredictedActionsForContext(actions: any[]): string {
  if (actions.length === 0) return ''

  const lines = actions.map((a: any) => {
    const urgencyIcon = a.urgency === 'critical' ? '🔴' : a.urgency === 'high' ? '🟠' : '🟡'
    const hasDraft = a.draft_content ? ' [draft ready]' : ''
    return `${urgencyIcon} ${a.title}${hasDraft} — ${a.description.slice(0, 100)}`
  })

  return `PRE-STAGED ACTIONS (predicted, ready to serve):\n${lines.join('\n')}`
}

// ── Regenerate on life event or severe routine break ──────────────

export async function regenerateOnEvent(reason: string): Promise<number> {
  console.log(`[predictor] Regenerating actions due to: ${reason}`)
  const pool = getPool()

  // Expire all current predictions — they may be stale
  await pool.query(
    "UPDATE predicted_actions SET status = 'invalidated' WHERE status = 'pending'"
  )

  return runActionPredictor()
}

// ── Helpers ───────────────────────────────────────────────────────

function safeParseJson(val: any, fallback: any): any {
  if (Array.isArray(val)) return val
  if (typeof val === 'string') {
    try { return JSON.parse(val) } catch { return fallback }
  }
  return fallback
}
